- name: Clone drastic git repo
  git:
    repo=git@github.com:UMD-DRASTIC/drastic.git
    dest="{{ install_dir }}/drastic"
    accept_hostkey=yes
    force=yes
    update=yes

- name: Clone drastic-web git repo
  git:
    repo="git@github.com:UMD-DRASTIC/drastic-web.git"
    dest="{{ install_dir }}/web/project"
    accept_hostkey=yes
    force=yes
    update=yes

- name: Copy settings
  template: src=settings.py dest="{{ install_dir }}/drastic"

- name: Restart the Drastic web service
  service: name=drastic-web state=restarted
  become: yes
  become_method: sudo
