---
##############################################################################
# System initialisation
# Install all of the required apt packages
##############################################################################
- name: Create log file directory
  file: path="{{ install_dir }}/log/" state=directory

- name: update apt-cache
  sudo: true
  apt: update_cache=yes # upgrade=full install_recommends=no

- name: Install useful packages
  apt: pkg={{ item }} state=installed install_recommends=no
  with_items:
    - build-essential
    - git
    - htop
    - iotop
    - vim
    - python-pip
    - python-virtualenv
  sudo: true

- name: Ensures /var/www/.python-eggs dir exists
  file: path=/var/www/.python-eggs state=directory owner=www-data
  sudo: true

- name: Clone git repo
  git: repo=git@bitbucket.org:archivea/indigo.git
       dest="{{ install_dir }}/indigo"
       key_file="{{ install_dir }}/.ssh/indigo_deployment_private_key"
       accept_hostkey=yes
       force=yes
#- name: Copy local source
#  synchronize: src=../indigo/ dest="{{ install_dir }}/indigo"
#  remote_user: vagrant

- name: Copy settings
  template: src=settings.py dest="{{ install_dir }}/indigo"
