---
##############################################################################
# System initialisation
# Install all of the required apt packages
##############################################################################
#- debug: msg="Waiting 1 minute for Cassandra to start - yes - really"
#- pause: minutes=1

- name: Waiting for Cassandra to start
  wait_for: path=/var/log/cassandra/system.log state=present

- name: Waiting for Cassandra to finish initialization
  wait_for: path=/var/log/cassandra/system.log search_regex="Created default superuser role 'cassandra'"

- name: update apt-cache
  sudo: true
  apt: update_cache=yes

- name: Install useful packages
  apt: pkg={{ item }} state=installed
  with_items:
    - build-essential
    - git
    - htop
    - iotop
    - vim
    - python-pip
    - python-virtualenv
  sudo: true

- name: Ensures /var/www/.python-eggs dir exists
  file: path=/var/www/.python-eggs state=directory owner=www-data
  sudo: true

- git: repo=https://{{ bb_user }}:{{ bb_pass }}@bitbucket.org/archivea/indigo.git
       dest=/usr/lib/indigo/indigo
  sudo: true
