---
##############################################################################
# System initialisation
# Install all of the required apt packages
##############################################################################
#- debug: msg="Waiting 1 minute for Cassandra to start - yes - really"
#- pause: minutes=1

- name: Waiting for Cassandra to start
  wait_for: path=/var/log/cassandra/system.log state=present

- name: Waiting for Cassandra to finish initialization
  wait_for: path=/var/log/cassandra/system.log search_regex="Created default superuser role 'cassandra'"

- name: Ensure we get the latest Mosquitto MQTT broker
  apt_repository: repo='ppa:mosquitto-dev/mosquitto-ppa'
  sudo: yes

- name: update apt-cache
  sudo: true
  apt: update_cache=yes

- name: Install useful packages
  apt: pkg={{ item }} state=installed
  with_items:
    - build-essential
    - git
    - htop
    - iotop
    - vim
    - python-pip
    - python-virtualenv
    - mosquitto
  sudo: true

- name: Start the MQTT broker
  service: name=mosquitto state=started
  sudo: yes

- name: Ensures /var/www/.python-eggs dir exists
  file: path=/var/www/.python-eggs state=directory owner=www-data
  sudo: true

- name: Clone git repo
  git: repo=git@bitbucket.org:archivea/indigo.git
       dest="{{ install_dir }}/indigo"
       key_file="{{ install_dir }}/.ssh/indigo_deployment_private_key"
       accept_hostkey=yes
       force=yes
#- name: Copy local source
#  synchronize: src=../indigo/ dest="{{ install_dir }}/indigo"
#  remote_user: vagrant

- name: Copy listener init script
  template: src=indigo-listener.conf dest=/etc/init/indigo-listener.conf
  sudo: yes

- name: Start the listener
  service: name=indigo-listener state=started
  sudo: yes

- name: Restart the Indigo web service
  service: name=indigo-web state=restarted
  sudo: yes
