- pip: name=cassandra-driver

# Download and install Cassandra from an archive
- name: Stat Archive
  stat: path=/home/drastic/apache-cassandra-{{cassandra_version}}-bin.tar.gz
  register: archive_stat

- name: Download archive
  get_url:
    url=http://mirrors.ibiblio.org/apache/cassandra/{{cassandra_version}}/apache-cassandra-{{cassandra_version}}-bin.tar.gz
    dest=/home/drastic
  when: not archive_stat.stat.exists

- name: Stat Cassandra
  stat: path=/var/lib/apache-cassandra-{{cassandra_version}}
  register: cassandra_stat

- name: Extract Cassandra
  unarchive:
    copy=no
    src=/home/drastic/apache-cassandra-{{cassandra_version}}-bin.tar.gz
    dest=/var/lib
  become: yes
  become_method: sudo
  when: not cassandra_stat.stat.exists

- name: Create Cassandra directory link
  file:
    path=/var/lib/cassandra
    src=/var/lib/apache-cassandra-{{cassandra_version}}
    state=link
  become: yes
  become_method: sudo

- name: Create Cassandra User
  user:
    name=cassandra
    system=yes
    home=/var/lib/cassandra
    shell=/bin/false
    state=present
  become: yes
  become_method: sudo

- name: Create Cassandra Group
  user:
    name=cassandra
    system=yes
    state=present
  become: yes
  become_method: sudo

- name: Change ownership of Cassandra directory
  file:
    path=/var/lib/apache-cassandra-{{cassandra_version}}
    state=directory
    owner=cassandra
    group=cassandra
    recurse=yes
  become: yes
  become_method: sudo

# This will restart Cassandra only if the configuration file has changed. See handlers/main.yaml
- name: Copy Cassandra configuration file
  template: src=cassandra.yaml dest=/var/lib/cassandra/conf/cassandra.yaml
  notify:
    - Restart Cassandra
  become: yes
  become_method: sudo

- name: Copy Cassandra init script
  template: src=cassandra.service dest=/etc/systemd/system/cassandra.service
  become: yes
  become_method: sudo
  notify: systemd daemon-reload

- name: Create cqlsh link
  file:
    path=/usr/local/bin/cqlsh
    src=/var/lib/cassandra/bin/cqlsh
    state=link
  become: yes
  become_method: sudo

- name: Create Cassandra cache directory
  file: path=/var/lib/cassandra/saved_caches state=directory mode=0775
  become: yes
  become_method: sudo

- name: Create Cassandra commitlog directory
  file: path=/var/lib/cassandra/commitlog state=directory mode=0770
  become: yes
  become_method: sudo

- name: Create Cassandra run directory
  file: path=/var/run/cassandra state=directory mode=0775
  become: yes
  become_method: sudo

- name: Change ownership of Cassandra log directory
  file: path=/var/log/cassandra state=directory owner=cassandra group=cassandra recurse=yes
  become: yes
  become_method: sudo

- name: Change ownership of Cassandra run directory
  file: path=/var/run/cassandra state=directory owner=cassandra group=cassandra
  become: yes
  become_method: sudo
