---
# This playbook deploys/installs a single node of the Indigo system

- name: Install indigo node
  remote_user: indigo
  hosts: indigo

  roles:
    - cassandra
    - indigo-agent
    - indigo-web

  # I don't like this because it puts my username and password into requirements.txt that persist on the server...
  # At least we should delete requirements.txt, but it might be better to download requirements.txt locally and feed
  # each row into Ansible.
  vars_prompt:
   - name: "bb_user"
     prompt: "Bitbucket Username"

   - name: "bb_pass"
     prompt: "Bitbucket Password"
     private: yes
