---
# This playbook deploys/installs a single node of the Indigo system

- name: install indigo node
  user: indigo
  hosts: indigo
  roles:
    - cassandra
    - indigo-node
  vars_prompt:
   - name: "bb_user"
     prompt: "Bitbucket Username"
   - name: "bb_pass"
     prompt: "Bitbucket Password"
     private: yes
