---
- hosts:  drastic-databases
  tasks:
  - debug: msg="Gathers the facts about db servers (IP addresses mainly)"

- name: Install drastic webserver
  remote_user: drastic
  hosts: drastic-webservers
  vars:
    https_mode: false

  roles:
    - drastic-node
    - drastic-web
    - drastic-listener
