---
- name: Install indigo webserver
  remote_user: indigo
  hosts: indigo-webservers
  vars:
    https_mode: false

  pre_tasks:
    - name: Copy bitbucket deployment key to the server
      copy: src=files/indigo_deployment_private_key dest="{{ install_dir }}/.ssh/indigo_deployment_private_key" mode=0600

  roles:
    - indigo-web
#    - indigo-listener

  post_tasks:
    - name: Delete bitbucket deployment key
      file: path="{{ install_dir }}/.ssh/indigo_deployment_private_key" state=absent