---
- name: Create drastic user
  hosts: drastic-webservers
  become: yes
  tasks:
  - user:
      name: drastic
      system: yes

- hosts:  drastic-databases
  tasks:
  - debug: msg="Gathering IP addresses of the Cassandra servers"

- name: Install drastic webserver
  hosts: drastic-webservers
  become: yes
  pre_tasks:
  - debug:
      msg: "NOTE: DEPLOYING LOCAL CODE"
    when: deploy_local_code
  roles:
    - drastic
    - django
    - nginx
