---
- hosts:  drastic-databases
  tasks:
  - debug: msg="Gathers the facts about db servers (IP addresses mainly)"

- name: Install drastic webserver
  remote_user: drastic
  hosts: drastic-webservers
  vars:
    https_mode: false

  pre_tasks:
    - name: Copy bitbucket deployment key to the server
      copy: content={{ drastic_deployment_private_key }} dest="{{ install_dir }}/.ssh/drastic_deployment_private_key" mode=0600

  roles:
    - drastic-web
    - drastic-listener

  post_tasks:
    - name: Delete bitbucket deployment key
      file: path="{{ install_dir }}/.ssh/drastic_deployment_private_key" state=absent
