---
- name: Create drastic user
  hosts: drastic-webservers
  become: yes
  tasks:
  - user:
      name: drastic
      system: yes

- hosts:  drastic-databases
  tasks:
  - debug: msg="Gathers the facts about db servers (IP addresses mainly)"

- name: Install drastic webserver
  hosts: drastic-webservers
  become: yes
  pre_tasks:
  - debug:
      msg: "NOTE: DEPLOYING LOCAL CODE"
    when: deploy_local_code
  - file:
      path: "{{ install_dir }}"
      state: directory
      owner: drastic
      group: drastic
      mode: 0755

  roles:
    - drastic-node
    - drastic-web
