---
##############################################################################
# Create the virtualenv where we will host the indigo-agent app
##############################################################################
- name: update apt-cache
  apt: update_cache=yes
  sudo: yes

- name: Manually create the agent virtualenv
  command: virtualenv "{{ install_dir }}/agent" creates="{{ install_dir }}/agent"

- git: repo="https://{{ bb_user }}:{{ bb_pass }}@bitbucket.org/archivea/indigo-agent.git"
       dest="{{ install_dir }}/agent/project"
       accept_hostkey=yes

- name: Install indigo agent into venv
  shell: "{{ install_dir }}/agent/bin/python setup.py develop"
  args:
    chdir: "{{ install_dir }}/agent/project"

- name: Install indigo lib into agent
  shell: "{{ install_dir }}/agent/bin/python setup.py develop"
  args:
    chdir: "{{ install_dir }}/indigo"

- name: "Copy init script"
  template: src=indigo-agent.conf dest=/etc/init/indigo-agent.conf
  sudo: yes