---
##############################################################################
# System initialisation
# Install all of the required apt packages
##############################################################################
- user:
    name: drastic
    system: yes
- file:
    path: "{{ install_dir }}"
    state: directory
    owner: drastic
    group: drastic
    mode: 0755
- name: Create log file directory
  file: path="{{ install_dir }}/log/" state=directory owner=drastic

- name: update apt-cache
  apt: update_cache=yes # upgrade=full install_recommends=no

- name: Install useful packages
  apt: pkg={{ item }} state=installed install_recommends=no
  with_items:
    - build-essential
    - git
    - python-pip
    - python-setuptools
    - python-virtualenv

- name: Ensures /var/www/.python-eggs dir exists
  file: path=/var/www/.python-eggs state=directory owner=www-data

- name: Clone git repo
  git:
    repo: https://github.com/UMD-DRASTIC/drastic.git
    dest: "{{ install_dir }}/drastic"
    accept_hostkey: yes
    force: yes
    update: yes
    version: master
  when: not deploy_local_code
  tags: code

- name: Copy local drastic lib sources
  synchronize:
    src: ../../../drastic/
    dest: "{{ install_dir }}/drastic"
    recursive: yes
  when: deploy_local_code
  tags: code
