---
##############################################################################
# System initialisation
# Install all of the required apt packages
##############################################################################
- name: Create log file directory
  file: path="{{ install_dir }}/log/" state=directory

- name: update apt-cache
  become: yes
  become_method: sudo
  apt: update_cache=yes # upgrade=full install_recommends=no

- name: Install useful packages
  apt: pkg={{ item }} state=installed install_recommends=no
  with_items:
    - build-essential
    - git
    - htop
    - iotop
    - vim
    - python-pip
    - python-setuptools
    - python-virtualenv
    - mosquitto
  become: yes
  become_method: sudo

- name: Ensures /var/www/.python-eggs dir exists
  file: path=/var/www/.python-eggs state=directory owner=www-data
  become: yes
  become_method: sudo

- name: Clone git repo
  git: repo=https://github.com/UMD-DRASTIC/drastic.git
       dest="{{ install_dir }}/drastic"
       accept_hostkey=yes
       force=yes
       update=yes
       version=master
  when: not deploy_local_code
  tags: code

- name: Copy local drastic lib sources
  synchronize:
    src: ../drastic/
    dest: "{{ install_dir }}/drastic"
    recursive: yes
  when: deploy_local_code
  tags: code

- name: Create drastic settings file
  template: src=settings.py dest="{{ install_dir }}/drastic"
  tags: code

- name: Start the MQTT broker
  service: name=mosquitto state=started
  sudo: yes
