---
##############################################################################
# System initialisation
# Install all of the required apt packages
##############################################################################
- name: Create log file directory
  file: path="{{ install_dir }}/log/" state=directory

- name: update apt-cache
  become: yes
  become_method: sudo
  apt: update_cache=yes # upgrade=full install_recommends=no

- name: Install useful packages
  apt: pkg={{ item }} state=installed install_recommends=no
  with_items:
    - build-essential
    - git
    - htop
    - iotop
    - vim
    - python-pip
    - python-setuptools
    - python-virtualenv
  become: yes
  become_method: sudo

- name: Ensures /var/www/.python-eggs dir exists
  file: path=/var/www/.python-eggs state=directory owner=www-data
  become: yes
  become_method: sudo

- name: Clone git repo
#  git: repo=/home/alloy/tmp/drastic_git/drastic.git
  git: repo=git@bitbucket.org:archivea/drastic.git
       dest="{{ install_dir }}/drastic"
       key_file="{{ install_dir }}/.ssh/drastic_deployment_private_key"
       accept_hostkey=yes
       force=yes
       update=yes
       version=develop
#- name: Copy local source
#  synchronize: src=../drastic/ dest="{{ install_dir }}/drastic"
#  remote_user: vagrant

- name: Copy settings
  template: src=settings.py dest="{{ install_dir }}/drastic"
