---
##############################################################################
# Create the virtualenv where we will host the indigo-web app
##############################################################################

#- name: Ensures {{ install_dir }}/web/project/static dir exists
#  file: path={{ install_dir }}/web/project/static state=directory
# Make writable
# {{ install_dir }}/web/project/static

- name: Create log file directory
  file: path="{{ install_dir }}/log/" state=directory

- name: update apt-cache
  apt: update_cache=yes
  sudo: true

- name: install packages for indigo web-ui
  apt: pkg={{ item }} state=installed
  with_items:
    - nginx
    - expect
  sudo: true

- name: Manually create the webapp virtualenv
  command: virtualenv "{{ install_dir }}/web" creates="{{ install_dir }}/web"

- git: repo="https://{{ bb_user }}:{{ bb_pass }}@bitbucket.org/archivea/indigo-web.git"
       dest="{{ install_dir }}/web/project"
       accept_hostkey=yes

- name: Install requirements
  pip:
    requirements="{{ install_dir }}/web/project/requirements.txt"
    virtualenv="{{ install_dir }}/web"

- name: Install indigo lib into webapp
  shell: "{{ install_dir }}/web/bin/python setup.py develop"
  args:
    chdir: "{{ install_dir }}/indigo"

- name: Copy init script
  template: src=indigo-web.conf dest=/etc/init/indigo-web.conf
  sudo: true

- name: Copy nginx config
  template: src=indigo-web.nginx dest=/etc/nginx/sites-enabled/default
  sudo: true

- name: Create the cassandra database
  command: "{{ install_dir }}/web/bin/indigo create"

- name: Collect static
  command: "{{ install_dir }}/web/bin/python {{ install_dir }}/web/project/manage.py collectstatic --noinput"

- name: Initialise Django database
  django_manage: command=syncdb app_path="{{ install_dir }}/web/project" virtual_env="{{ install_dir }}/web/"

- name: Set up database
  command: "{{ install_dir }}/web/bin/python {{ install_dir }}/web/bin/indigo create"

- name: Create default user
  script: init_user.expect "{{ install_dir }} {{ default_user_name }} {{ default_password }}"
  ignore_errors: yes

- name: Create default group
  command: "{{ install_dir }}/web/bin/python {{ install_dir }}/web/bin/indigo group-create {{ default_group }} {{ default_user_name }}"

- name: Start nginx
  service: name=nginx state=restarted
  sudo: true

- name: Start the Indigo web service
  service: name=indigo-web state=started
  sudo: yes