---
##############################################################################
# Create the virtualenv where we will host the indigo-web app
##############################################################################

#- name: Ensures /usr/lib/indigo/web/project/static dir exists
#  file: path=/usr/lib/indigo/web/project/static state=directory
# Make writable
# /usr/lib/indigo/web/project/static

- name: update apt-cache
  sudo: true
  apt: update_cache=yes

- name: install packages for indigo web-ui
  apt: pkg={{ item }} state=installed
  with_items:
    - nginx
  sudo: true

- name: Manually create the webapp virtualenv
  command: virtualenv /usr/lib/indigo/web creates="/usr/lib/indigo/web"
  sudo: true

- git: repo=https://{{ bb_user }}:{{ bb_pass }}@bitbucket.org/archivea/indigo-web.git
       dest=/usr/lib/indigo/web/project
       accept_hostkey=yes
  sudo: true

- name: Install requirements
  pip:
    requirements=/usr/lib/indigo/web/project/requirements.txt
    virtualenv=/usr/lib/indigo/web
  sudo: true

- name: Install indigo lib into webapp
  shell: "/usr/lib/indigo/web/bin/python setup.py develop"
  args:
    chdir: /usr/lib/indigo/indigo
  sudo: true

- name: Copy init script
  template: src=indigo-web.conf dest=/etc/init/indigo-web.conf
  sudo: true

- name: Copy nginx config
  template: src=indigo-web.nginx dest=/etc/nginx/sites-enabled/default
  sudo: true

- name: Create the cassandra database
  command: /usr/lib/indigo/web/bin/indigo create
  sudo: true

- name: Collect static
  command: /usr/lib/indigo/web/bin/python /usr/lib/indigo/web/project/manage.py collectstatic --noinput
  sudo: true

- service: name=nginx state=restarted
  sudo: true
