- name: Install Cassandra Python driver and CQLSH tool
  pip: name=cassandra-driver
  become: yes

- name: Install Cassandra (Apt)
  become: yes
  block:
  - apt_repository: repo="deb http://www.apache.org/dist/cassandra/debian 311x main" state=present
  - apt_key: url=https://www.apache.org/dist/cassandra/KEYS state=present
  - apt: package=cassandra update_cache=yes allow_unauthenticated=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Cassandra (Yum)
  become: yes
  block:
  - yum_repository:
      name: cassandra
      description: Apache Cassandra
      baseurl: https://www.apache.org/dist/cassandra/redhat/311x/
      gpgcheck: no
      repo_gpgcheck: no
      gpgkey: https://www.apache.org/dist/cassandra/KEYS
  - yum:
      name: cassandra
      update_cache: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

# This will restart Cassandra only if the configuration file has changed. See handlers/main.yaml
- name: Copy Cassandra configuration file
  template: src=cassandra.yaml dest=/etc/cassandra/cassandra.yaml
  notify:
    - Restart Cassandra
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Copy Cassandra configuration file
  template: src=cassandra.yaml dest=/etc/cassandra/conf/cassandra.yaml
  notify:
    - Restart Cassandra
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Create Cassandra cache directory
  file: path=/var/lib/cassandra/saved_caches state=directory mode=0775 owner=cassandra group=cassandra
  become: yes

- name: Create Cassandra cache directory
  file: path=/var/lib/cassandra/hints state=directory mode=0775 owner=cassandra group=cassandra
  become: yes

- name: Create Cassandra commitlog directory
  file: path=/var/lib/cassandra/commitlog state=directory mode=0770 owner=cassandra group=cassandra
  become: yes
  notify: Restart Cassandra

- name: Set OS user limits
  become: yes
  blockinfile:
    dest: /etc/security/limits.conf
    insertafter: EOF
    block: |
      * - memlock unlimited
      * - nofile 100000
      * - nproc 32768
      * - as unlimited
