- name: Install Cassandra Python driver and CQLSH tool
  pip: name=cassandra-driver-dse
- pip: name=geomet

- name: Add Datastax APT Repository
  apt_repository: repo="deb http://{{ datastax_email }}:{{ datastax_password }}@debian.datastax.com/enterprise stable main" state=present
  become: yes

- name: Add Datastax APT Key
  apt_key: url=http://debian.datastax.com/debian/repo_key state=present
  become: yes

- name: Install Datastax Enterprise packages
  apt: package={{ item }}={{ datastax_version }} update_cache=yes allow_unauthenticated=yes
  become: yes
  with_items:
    - dse-full
    - dse
    - dse-hive
    - dse-pig
    - dse-demos
    - dse-libcassandra
    - dse-libspark
    - dse-libgraph
    - dse-libsolr
    - dse-libtomcat
    - dse-libsqoop
    - dse-liblog4j
    - dse-libmahout
    - dse-libhadoop2-client
    - dse-libhadoop2-client-native

# This will restart Cassandra only if the configuration file has changed. See handlers/main.yaml
- name: Replace Cassandra configuration file
  template: src=cassandra.yaml dest=/etc/dse/cassandra/cassandra.yaml
  become: yes

- name: Enable DSE Graph
  when: enable_datastax_graph
  lineinfile:
    dest: /etc/default/dse
    regexp: '^GRAPH_ENABLED='
    line: 'GRAPH_ENABLED=1'
  become: yes

- name: Enable Apache Spark
  when: enable_datastax_spark
  lineinfile:
    dest: /etc/default/dse
    regexp: '^SPARK_ENABLED='
    line: 'SPARK_ENABLED=1'
  become: yes

- name: Set Cassandra Package Install User Limits
  copy: src=files/cassandra.conf dest=/etc/security/limits.d/cassandra.conf
  become: yes

- name: Restart Datastax
  service: name=dse state=started
  become: yes
  ignore_errors: yes
