---
##############################################################################
# Java
# This must be Oracle's Java, and also should use libjna for performance.
##############################################################################

- name: Check directories
  stat: path={{ item }}
  register: st
  with_items: '{{ cassandra_data_dirs }}'

- name: Complain
  fail: msg='Cassandra data directory {{ item.item }} does not exist or is not set properly'
  when: item.stat.isdir is not defined or not item.stat.isdir
  with_items: "{{ st.results }}"

- name: Installation dependencies
  apt: pkg=python-apt state=installed update_cache=yes force=yes
  become: yes
  become_method: sudo

- name: Add PPA for Oracle Java 8
  apt_repository: repo='ppa:webupd8team/java' state=present
  become: yes
  become_method: sudo

- name: Select and agree to licence
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  become: yes
  become_method: sudo

- name: System dependencies
  become: yes
  become_method: sudo
  apt: pkg={{ item }} state=installed update_cache=yes force=yes
  with_items:
    - oracle-java8-installer
    - libjna-java
    - python-pip
    - git
    - curl
    - ntp
    # For client machine ...
    - libev4
    - libev-dev
    - build-essential
    - python-dev

##############################################################################
# Cassandra or Datastax Enterprise
##############################################################################

- name: Install Cassandra (open source)
  include: cassandra_install.yml
  when: not use_datastax

- name: Install Datastax Enterprise
  include: datastax_install.yml
  when: use_datastax

- name: Set Virtual Memory Resource Limit
  lineinfile: dest=/etc/sysctl.conf line="vm.max_map_count = 1048575"
  become: yes

- name: Enable PAM Session Limits
  lineinfile:
    dest=/etc/pam.d/su
    line="session    required   pam_limits.so"
    insertafter="# session    required   pam_limits.so"
  become: yes

- name: Remove Swap Space
  lineinfile: dest=/etc/fstab state=absent regexp="  swap  "
  become: yes

- name: Make resource limits effective
  become: yes
  command: sysctl -p

# Directories were already checked to exist at the top. We don't want to create
# new directories when remote volumes are not properly mounted yet.
- name: Set ownership and permissions of Cassandra data directory
  file: path={{ item }} state=directory mode=0755 owner=cassandra group=cassandra recurse=yes
  become: yes
  become_method: sudo
  with_items: '{{ cassandra_data_dirs }}'

- name: Create Cassandra log directory
  file: path=/var/log/cassandra/log state=directory mode=0770 owner=cassandra
  become: yes
  become_method: sudo

- name: Restart services
  meta: flush_handlers

- name: Pause for Cassandra to come online
  pause:
    seconds: "{{ cassandra_restart_seconds|int }}"

- name: Create drastic keyspace as Cassandra becomes available
  command: |
    cqlsh \
    --connect-timeout=30 \
    --request-timeout=30 \
    {{ hostvars[inventory_hostname]['ansible_' ~ cassandra_interface]['ipv4']['address'] }} \
    -e "CREATE KEYSPACE IF NOT EXISTS drastic WITH replication = {'class': 'SimpleStrategy', 'replication_factor': {{ cassandra_replication_factor }} };"
  register: cqlsh_ready
  until: cqlsh_ready.rc is defined and cqlsh_ready.rc == 0
  delay: 10
  retries: 5
  # environment:
  #  CQLSH_NO_BUNDLED: TRUE

- debug:
    msg: "ansible_hostname is {{ ansible_hostname }}, ansible_nodename is {{ ansible_nodename }}"
  tags: graph

- name: Configure gremlin-console to connect to correct IP
  template:
    src: gremlin-console-remote.yaml
    dest: /etc/dse/graph/gremlin-console/conf/remote.yaml
    owner: cassandra
    group: cassandra
  become: yes
  tags: graph
  when: ansible_hostname == cassandra_seed_server

- name: Place graph and schema creation into gremlin-console init script
  copy: src=mydse-init.groovy dest=/etc/dse/graph/gremlin-console/scripts/dse-init.groovy owner=cassandra group=cassandra
  become: yes
  tags: graph
  when: ansible_hostname == cassandra_seed_server

- name: Start DSE gremlin-console to initialize drastic graph
  shell: |
    dse gremlin-console &
    sleep 60
    kill %1
  ignore_errors: yes
  tags: graph
  when: ansible_hostname == cassandra_seed_server

- name: Reset gremlin-console init script to usual
  copy: src=dse-init.groovy dest=/etc/dse/graph/gremlin-console/scripts/dse-init.groovy owner=cassandra group=cassandra
  become: yes
  tags: graph
  when: ansible_hostname == cassandra_seed_server
