- apt_repository:
    repo: deb-src http://us.archive.ubuntu.com/ubuntu/ {{ item }}
    state: present
  become: yes
  with_items:
    - xenial main restricted
    - xenial-updates main restricted
    - xenial universe
    - xenial-updates universe
    - xenial multiverse
    - xenial-updates multiverse

- apt:
    state: build-dep
    name: python2.7
    update_cache: yes
  become: yes

- name: Stat Python Installer Archive
  stat:
    path: "{{ install_dir }}/Python-2.7.10.tgz"
  register: archive_stat
  become: yes

- name: Download Python Installer Archive
  get_url:
    url: http://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
    dest: "{{ install_dir }}"
  when: not archive_stat.stat.exists
  become: yes

- name: Stat Python Installer Dir
  stat:
    path: "{{ install_dir }}/Python-2.7.10"
  register: installerdir_stat
  become: yes

- name: Extract Python Installer Dir
  unarchive:
    copy: no
    src: "{{ install_dir }}/Python-2.7.10.tgz"
    dest: "{{ install_dir }}"
  become: yes
  when: not installerdir_stat.stat.exists

- file:
    path: "{{ install_dir }}/localpython"
    state: directory
    owner: drastic
  become: yes

- command: "./configure --prefix={{ install_dir }}/localpython"
  args:
    chdir: "{{ install_dir }}/Python-2.7.10"
  become: yes

- command: make install
  args:
    chdir: "{{ install_dir }}/Python-2.7.10"
  become: yes

- file:
    path: "{{ install_dir }}/localpython"
    state: directory
    owner: drastic
    recurse: yes
  become: yes
