---

# Note that handlers are run in the order defined here.
- name: systemctl daemon-reload
  command: systemctl daemon-reload
  become: yes

- name: Restart Cassandra
  service: name=cassandra.service enabled=yes state=restarted
  become: yes

- name: Restart Datastax
  service: name=dse enabled=yes state=restarted
  become: yes
