---
# No longer needed on Xenial release
# - name: Ensure we get the latest Mosquitto MQTT broker
#   apt_repository: repo='ppa:mosquitto-dev/mosquitto-ppa'
#   sudo: yes

- name: Install useful packages
  apt: pkg={{ item }} state=installed install_recommends=no
  with_items:
    - mosquitto
  sudo: yes

- name: Start the MQTT broker
  service: name=mosquitto state=started
  sudo: yes

- name: Create script cache directory
  file: name='{{ install_dir }}/scripts_cache' state=directory

- name: Get the latest Docker
  get_url: dest='{{ temp_dir }}/install_docker.sh' url=https://get.docker.com/ mode=0755
  sudo: yes
  register: getdocker

- name: Install Docker
  command: '{{ temp_dir }}/install_docker.sh'
  sudo: yes
  when: getdocker.changed

- name: Add the user to the docker group
  user: name={{ ansible_user_id }} groups=docker append=yes
  sudo: yes

- name: Copy Dockerfile
  copy: src=Dockerfile dest='{{ install_dir }}/Dockerfile'
  register: dockerfile

- name: Create Docker image
  command: /usr/bin/docker build -t alloy_python '{{ install_dir }}'
  sudo: yes
  when: dockerfile.changed
  environment:
    TMPDIR: '{{ temp_dir }}'

- name: Install requirements
  pip: name={{ item }} virtualenv="{{ install_dir }}/listener"
  with_items:
    - docopt
    - paho-mqtt
    - python-magic
    - gevent
  environment:
    TMPDIR: '{{ temp_dir }}'

- name: Install drastic lib
  shell: "{{ install_dir }}/listener/bin/python setup.py develop"
  environment:
    TMPDIR: '{{ temp_dir }}'
  args:
    chdir: "{{ install_dir }}/drastic"

- name: Copy listener service configuration
  template: src=drastic-listener.service dest=/etc/systemd/system/drastic-listener.service
  sudo: yes

- name: Start the listener
  service: name=drastic-listener state=restarted
  sudo: yes

- name: Restart the Drastic web service
  service: name=drastic-web state=restarted
  sudo: yes
  when: drastic-web-installed is defined
