- name: Copy bitbucket deployment key to the server
  copy: content={{ indigo_deployment_private_key }} dest="{{ install_dir }}/.ssh/indigo_deployment_private_key" mode=0600

- name: Clone indigo git repo
  git:
    repo=git@bitbucket.org:archivea/indigo.git
    dest="{{ install_dir }}/indigo"
    key_file="{{ install_dir }}/.ssh/indigo_deployment_private_key"
    accept_hostkey=yes
    force=yes
    update=yes
    version=develop

- name: Clone indigo-web git repo
  git:
    repo="git@bitbucket.org:archivea/indigo-web.git"
    dest="{{ install_dir }}/web/project"
    key_file="{{ install_dir }}/.ssh/indigo_deployment_private_key"
    accept_hostkey=yes
    force=yes
    update=yes
    version=develop

- name: Copy settings
  template: src=settings.py dest="{{ install_dir }}/indigo"

- name: Restart the Indigo web service
  service: name=indigo-web state=restarted
  become: yes
  become_method: sudo

- name: Delete bitbucket deployment key
  file: path="{{ install_dir }}/.ssh/indigo_deployment_private_key" state=absent
